name: docker-build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
    
    - name: Create Dockerfile
      run: |
       echo "FROM node:22-alpine" > Dockerfile
       echo "WORKDIR /app" >> Dockerfile
       echo "COPY package*.json ./" >> Dockerfile
       echo "RUN npm install" >> Dockerfile
       echo "COPY . ./" >> Dockerfile
       echo "EXPOSE 3000" >> Dockerfile
       echo "CMD ["npm", "start"]" >> Dockerfile

    - name: Build docker image  
      run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/tecno-insumos:latest .

    - name: Push Docker image to DockerHub
      run: docker push ${{ vars.DOCKERHUB_USERNAME }}/tecno-insumos:latest
  
   
      
      




