name: docker-build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create Dockerfile
      run: |
       echo 'FROM node:22-alpine' > Dockerfile
       echo 'WORKDIR /app' >> Dockerfile
       echo 'COPY package*.json ./' >> Dockerfile
       echo 'RUN npm install' >> Dockerfile
       echo 'COPY . .' >> Dockerfile
       echo 'EXPOSE 3000' >> Dockerfile
       echo 'CMD ["npm", "start"]' >> Dockerfile

    - name: Build docker image  
      run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/tecno-insumos:latest .

    - name: Verify Docker image
      run: |
        docker run -d -p 3000:3000 ${{ vars.DOCKERHUB_USERNAME }}/tecno-insumos:latest
        sleep 5
        curl -f http://localhost:3000

    - name: Log in to DockerHub
      if: success() 
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
    
    - name: Push Docker image to DockerHub
      if: success() 
      run: docker push ${{ vars.DOCKERHUB_USERNAME }}/tecno-insumos:latest
      
      




