name: docker-build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
    
    - name: Create Dockerfile
      run: |
       echo "FROM node:24-alpine"
       echo "WORKDIR /app"
       echo "COPY package*.json ./"
       echo "RUN npm install"
       echo "COPY . ./"
       echo "EXPOSE 3000"
       echo "CMD ["npm", "start"]" 

    - name: Build docker image  
      run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/tecno-insumos:latest .

    - name: Push Docker image to DockerHub
      run: docker push ${{ vars.DOCKERHUB_USERNAME }}/tecno-insumos:latest
  
   
      
      




