name: Build Docker Image

on:
  workflow_run:
    workflows: ["Test update"]
    types: [completed]

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        run: 
          git clone https://github.com/${{ github.repository }} tecno-insumos
          cd tecno-insumos
          git checkout ${{ github.event.workflow_run.head_branch }}

      - name: Install Docker
        run: docker --version

      - name: Login Docker
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t yaboleo/tecno-insumos:latest .
    
      - name: Push Docker image
        run: docker push yaboleo/tecno-insumos:latest
