name: Test & PR

on:
  push:
    branches: [dev]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Node.js
      run: curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - && sudo apt-get install -y nodejs

    - name: Verify Node.js and npm versions
      run: node -v && npm -v

    - name: Checkout dev branch
      uses: actions/checkout@v4
      with:
        ref: dev
        fetch-depth: 0 

    - name: Run tests
      run: |
        npm install
        npm test

    - name: Create Pull Request to main
      if: success()
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: https://github.com/LeoYab/tecno-insumos.git
      run: |
        curl -X POST -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/$REPO/pulls \
          -d '{
            "title": "Auto PR",
            "head": "dev",
            "base": "main",
            "body": "Tests passed. Creating pull request from dev to main."
          }'
