name: Test & PR

on:
  push:
    branches: [dev]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Node.js
      run: curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - && sudo apt-get install -y nodejs

    - name: Verify Node.js and npm versions
      run: node -v && npm -v

    - name: Checkout dev branch
      uses: actions/checkout@v4
      with:
        ref: dev
        fetch-depth: 0 

    - name: Run tests
      run: |
        npm install
        npm test

    - name: Create Pull Request to main
      if: success()
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: "Auto PR: Sync dev to main"
        title: "Auto PR"
        body: "Tests passed. Creating pull request from dev to main."
        base: main
        branch: dev
        token: ${{ secrets.GITHUB_TOKEN }}
