name: Test & PR

on: 
  push:
    branches: [dev]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Install Node.js
      run: curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - && sudo apt-get install -y nodejs

    - name: Verify Node.js and npm versions  
      run: node -v && npm -v

    - name: Checkout repo at dev
      uses: actions/checkout@v4
      with:
        ref: dev

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Create Pull Request
      if: success()
      uses: devops-infra/action-pull-request@v0.5.5
      with:
        source_branch: dev
        target_branch: main
        title: "Auto PR"
        body: "Tests passed. Push PR from dev to main."
        github_token: ${{ secrets.GITHUB_TOKEN }}
