name: Test & PR

on:
  push:
    branches: [dev]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Node.js
      run: curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - && sudo apt-get install -y nodejs

    - name: Verify Node.js and npm versions
      run: node -v && npm -v

    - name: Checkout dev branch
      run: |
        git clone --branch=dev https://github.com/${{ github.repository }}.git
        cd ${{ github.event.repository.name }}
        git status
        echo "Install dependencies and run tests"
        npm install
        npm test

    - name: Create Pull Request to main
      if: success()
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/pulls \
          -d '{
            "title": "Auto PR to main",
            "body": "PR created automatically to main.",
            "head": "dev",
            "base": "main"
          }'