name: Test update

on: 
  push:
    branches: [ test ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Clone repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm test
    
    - name: Push Request
      if: success() 
      uses: devops-infra/action-pull-request@v0.5.5
      with:
        source_branch: test
        target_branch: main
        title: "Auto PR"
        body: "Tests passed. Push PR from test to main."
        github_token: ${{ secrets.GITHUB_TOKEN }}



       
